name: GitHub Release on version bump

on:
  push:
    branches: [main]
    paths:
      - 'DESCRIPTION'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from DESCRIPTION
        id: get_version
        run: |
          VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_check
        run: |
          git fetch --tags
          TAG_EXISTS=$(git tag -l "v${{ steps.get_version.outputs.version }}")
          if [ -z "$TAG_EXISTS" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Create and push Git tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "v${{ steps.get_version.outputs.version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "v${{ steps.get_version.outputs.version }}"

      - name: Create GitHub Release
        if: steps.tag_check.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body: |
            See [NEWS.md](https://github.com/${{ github.repository }}/blob/main/NEWS.md) for a detailed changelog.
